export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
# export MANPATH="/usr/local/man:$MANPATH"

#Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='emacs'
else
  export EDITOR='subl'
fi

#256 COLORS
export TERM="xterm-256color"

#editor
#export EDITOR='emacs'

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"
