# JAVA
# jEnv
eval "$(jenv init -)"
java8=`/usr/libexec/java_home -v "1.8*"`
java10=`/usr/libexec/java_home`
export JAVA_HOME=$java8
# For Intellij
launchctl setenv JAVA_HOME $java8

export EDITOR="nvim"
export MYNVIMRC="~/.config/nvim/init.vim"
export ALTERNATE_EDITOR=""
export TERM="screen-256color"
export SSH_KEY_PATH="~/.ssh/id_rsa"
export VIMRUNTIME="/usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime"
export NVIMRUNTIME="/usr/local/Cellar/neovim/0.2.2_1/share/nvim/runtime"

PATH=/bin:/usr/bin:/usr/local/bin:${PATH}
PATH=$HOME/.jenv/bin:$PATH

typeset -U PATH
