export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/spiros/chruby-0.3.8/bin:/home/spiros/.gem/ruby/2.3.0/bin:/home/spiros/neovim/bin"
# export MANPATH="/usr/local/man:$MANPATH"

#Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='emacs'
else
  export EDITOR='subl'
fi

export ALTERNATE_EDITOR=""

#256 COLORS
export TERM="xterm-256color"

#editor
#export EDITOR='emacs'

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"


# chruby
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
chruby 2.3.0

#REMAP CAPS LOCK to CTRL
gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
