# Environmental variables
export MANPATH="/usr/local/man:$MANPATH"
export EDITOR='nvim'
export MYNVIMRC='~/.config/nvim/init.vim'
export ALTERNATE_EDITOR=""
export TERM="xterm-256color"
#export TERM="screen-256color"
export SSH_KEY_PATH="~/.ssh/id_rsa"
export VIMRUNTIME="/usr/share/nvim/runtime"
export NVIMRUNTIME="/usr/share/nvim/runtime"
export PYTHONPATH="/usr/lib/python3.8/site-packages"
export JAVA_HOME="$HOME/.sdkman/candidates/java/current"
# export PATH="$PATH:`yarn global bin`"

# PATH
PATH=$(paste -d ":" -s << EOF
$PATH
$HOME/dotfiles/scripts
$HOME/.local/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
EOF
)
typeset -U PATH

# https://vi.stackexchange.com/questions/7644/use-vim-with-virtualenv/7654#7654
if [[ -n $VIRTUAL_ENV && -e "${VIRTUAL_ENV}/bin/activate" ]]; then
  source "${VIRTUAL_ENV}/bin/activate"
fi


#REMAP CAPS LOCK to CTRL
#gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/base16-material.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
